/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiValidateSpatialDataRouteImport } from './routes/api/validate-spatial-data'
import { Route as ApiAiChatRouteImport } from './routes/api/ai-chat'
import { Route as ApiMockScenarioRouteImport } from './routes/api/mock.$scenario'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiValidateSpatialDataRoute = ApiValidateSpatialDataRouteImport.update({
  id: '/api/validate-spatial-data',
  path: '/api/validate-spatial-data',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAiChatRoute = ApiAiChatRouteImport.update({
  id: '/api/ai-chat',
  path: '/api/ai-chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMockScenarioRoute = ApiMockScenarioRouteImport.update({
  id: '/api/mock/$scenario',
  path: '/api/mock/$scenario',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/ai-chat': typeof ApiAiChatRoute
  '/api/validate-spatial-data': typeof ApiValidateSpatialDataRoute
  '/api/mock/$scenario': typeof ApiMockScenarioRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/ai-chat': typeof ApiAiChatRoute
  '/api/validate-spatial-data': typeof ApiValidateSpatialDataRoute
  '/api/mock/$scenario': typeof ApiMockScenarioRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/ai-chat': typeof ApiAiChatRoute
  '/api/validate-spatial-data': typeof ApiValidateSpatialDataRoute
  '/api/mock/$scenario': typeof ApiMockScenarioRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api/ai-chat'
    | '/api/validate-spatial-data'
    | '/api/mock/$scenario'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api/ai-chat'
    | '/api/validate-spatial-data'
    | '/api/mock/$scenario'
  id:
    | '__root__'
    | '/'
    | '/api/ai-chat'
    | '/api/validate-spatial-data'
    | '/api/mock/$scenario'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiAiChatRoute: typeof ApiAiChatRoute
  ApiValidateSpatialDataRoute: typeof ApiValidateSpatialDataRoute
  ApiMockScenarioRoute: typeof ApiMockScenarioRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/validate-spatial-data': {
      id: '/api/validate-spatial-data'
      path: '/api/validate-spatial-data'
      fullPath: '/api/validate-spatial-data'
      preLoaderRoute: typeof ApiValidateSpatialDataRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ai-chat': {
      id: '/api/ai-chat'
      path: '/api/ai-chat'
      fullPath: '/api/ai-chat'
      preLoaderRoute: typeof ApiAiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/mock/$scenario': {
      id: '/api/mock/$scenario'
      path: '/api/mock/$scenario'
      fullPath: '/api/mock/$scenario'
      preLoaderRoute: typeof ApiMockScenarioRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiAiChatRoute: ApiAiChatRoute,
  ApiValidateSpatialDataRoute: ApiValidateSpatialDataRoute,
  ApiMockScenarioRoute: ApiMockScenarioRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
